"""ZPool management operations."""


class ZPoolMixin:
    """Mixin providing ZPool management operations."""
    
    def create_zpool(self, size_gib: int = 125, volume_type: str = "gp3"):
        """
        Create a new zpool (async operation).
        
        Note: zpool_id is auto-generated by the API.
        
        Args:
            size_gib: Size in GiB (must be 125 during beta)
            volume_type: EBS volume type ('gp3' or 'sc1')
            
        Returns:
            Response with status_code 202, zpool_id, and job_id
        """
        from .._generated.api.zpools import post_zpool
        from .._generated.models.post_zpool_body import PostZpoolBody, PostZpoolBodyNewSizeInGib, PostZpoolBodyVolumeType
        
        auth_client = self._auth.get_authenticated_client()
        
        # Convert to enum types
        size_enum = PostZpoolBodyNewSizeInGib(size_gib)
        vol_type_enum = PostZpoolBodyVolumeType(volume_type)
        
        return post_zpool.sync_detailed(
            client=auth_client,
            body=PostZpoolBody(new_size_in_gib=size_enum, volume_type=vol_type_enum)
        )
    
    def list_zpools(self):
        """
        List all zpools.
        
        Returns:
            Response with status_code and parsed list of zpools
        """
        from .._generated.api.zpools import get_zpools
        
        auth_client = self._auth.get_authenticated_client()
        return get_zpools.sync_detailed(client=auth_client)
    
    def delete_zpool(self, zpool_id: str):
        """
        Delete a zpool (sync operation).
        
        Args:
            zpool_id: The zpool_id to delete
            
        Returns:
            Response with status_code 200
        """
        from .._generated.api.zpools import delete_zpool_zpool_id
        
        auth_client = self._auth.get_authenticated_client()
        return delete_zpool_zpool_id.sync_detailed(client=auth_client, zpool_id=zpool_id)
    
    def scrub_zpool(self, zpool_id: str):
        """
        Start scrub on a zpool (async operation).
        
        Args:
            zpool_id: The zpool_id to scrub
            
        Returns:
            Response with status_code 202 and job_id
        """
        from .._generated.api.zpools import post_zpool_zpool_id_scrub
        
        auth_client = self._auth.get_authenticated_client()
        return post_zpool_zpool_id_scrub.sync_detailed(client=auth_client, zpool_id=zpool_id)
    
    def modify_zpool(self, zpool_id: str, target_volume_type: str):
        """
        Change a zpool's EBS volume type (fire-and-forget operation).
        
        Directly calls EBS ModifyVolume on each volume to change type (gp3 <-> sc1).
        Does not create a job. Monitor progress via list_zpools() to see volume optimization status.
        
        Args:
            zpool_id: The zpool_id to modify
            target_volume_type: Target EBS volume type (gp3 or sc1)
            
        Returns:
            Response with status_code 202 and summary of submitted modifications
        """
        from .._generated.api.zpools import post_zpool_zpool_id_modify
        from .._generated.models.post_zpool_zpool_id_modify_body import PostZpoolZpoolIdModifyBody
        from .._generated.models.post_zpool_zpool_id_modify_body_volume_type import PostZpoolZpoolIdModifyBodyVolumeType
        
        auth_client = self._auth.get_authenticated_client()
        
        # Convert string to enum type
        vol_type_enum = PostZpoolZpoolIdModifyBodyVolumeType(target_volume_type)
        
        return post_zpool_zpool_id_modify.sync_detailed(
            client=auth_client,
            zpool_id=zpool_id,
            body=PostZpoolZpoolIdModifyBody(volume_type=vol_type_enum)
        )
